### ISSUE TITLE
Bug for private mode

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [blackwind/reload-plus#3] opened 2016-03-12 16:44 UTC
I am using Firefox 45 on Windows 10. When I launch a private window of Firefox via right-click the icon pinned at taskbar, this addon seems not friendly to the private mode, the commands tooltip and context menu are disappeared.

**Comment by blackwind** [comment] 2016-03-12 23:58
Private mode was fixed in v5.0.0. If you're not using the latest version of R+, please update; if you are, you'll have to send along more detailed reproduction instructions, as I'm unable to reproduce on my end based on what you've written thus far.

**Comment by KrasnayaPloshchad** [comment] 2016-03-13 04:22
I’m using v5.0.3, I just opening private window firstly when I found this bug.

**Comment by blackwind** [comment] 2016-03-13 05:52
I'm not sure what to tell you, then. When I open a private window, on my end, R+ continues to function correctly in that window. This must be a conflict with another add-on.

Disable all your add-ons except R+ and see if the problem persists. If it doesn't, re-enable each add-on one by one until you find the culprit. If it _does_ persist, create a new Firefox profile and try again there.

If this ends up being a conflict with another add-on, I'll evaluate whether or not it's R+ at fault and take action if it is, which I doubt. More likely, I'll have to refer you to the other add-on's developers. If it's _not_ a conflict and it still happens in a clean profile, I'm fresh out of ideas. Until I can reproduce, unfortunately, there's very little I can do.

**Comment by KrasnayaPloshchad** [comment] 2016-03-13 08:30
I have removed my Firefox profile, but when I opened Firefox via `"C:\Program Files\Mozilla Firefox\firefox.exe" -private-window`, re-installed R+, the problem is appearing again.

**Comment by blackwind** [comment] 2016-03-13 08:35
Then I'm out of ideas. Works for me.

**Comment by KrasnayaPloshchad** [comment] 2016-03-18 07:45
Then when I opened second private window, they works.

**Comment by blackwind** [comment] 2016-03-18 07:50
Consider using [Private Tab](https://addons.mozilla.org/firefox/addon/private-tab/) for your private browsing so you don't have to open new windows at all.

**Closed as completed** 2016-03-26 08:10 UTC
Labels: bug, invalid

**Comment by KrasnayaPloshchad** [comment] 2016-04-04 15:01
So maybe we can report to Mozillla.

**Comment by KrasnayaPloshchad** [comment] 2017-01-26 07:14
The newest version (as of v5.2.0) now works pretty on all private windows, thank you.

**Comment by blackwind** [comment] 2017-01-26 07:21
I didn't make any changes related to private mode in this release, but glad to hear it's working for you now!
